server:
  port: 8081
spring:
  rabbitmq:
    host: 47.116.68.208
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)